### ISSUE TITLE
Can´t display table

### ISSUE THREAD

**Issue by ProblemKidS** [volosoft/jtable#2249]
After I set everything up. I don't see anything, even a table without data is missing. Please HELP.
this is what web console show me : 
Uncaught ReferenceError: jQuery is not definedat jquery-ui-1.9.2.min.js:5

jquery.jtable.min.js:25 Uncaught TypeError: c.widget is not a functionat jquery.jtable.min.js:25 at jquery.jtable.min.js:55
8Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure font '<URL>'. This request has been blocked; the content must be served over HTTPS.
Index:1 Mixed Content: The page at 'https://localhost:44391/Home/Index' was loaded over HTTPS, but requested an insecure font 'http://themes.googleusercontent.com/static/fonts/opensans/v6/DXI1ORHCpsQm3Vp6mXoaTRa1RVmPjeKy21_GQJaLlJI.woff'. 
This request has been blocked; the content must be served over HTTPS.
Index:1 Mixed Content: The page at 'https://localhost:44391/Home/Index' was loaded over HTTPS, but requested an insecure font 'http://themes.googleusercontent.com/static/fonts/opensans/v6/PRmiXeptR36kaC0GEAetxrsuoFAk0leveMLeqYtnfAY.woff'. This request has been blocked; the content must be served over HTTPS.
Index:1 Mixed Content: The page at 'https://localhost:44391/Home/Index' was loaded over HTTPS, but requested an insecure font 'http://themes.googleusercontent.com/static/fonts/opensans/v6/u-WUoqrET9fUeobQW7jkRT8E0i7KZn-EPnyo3HZu7kw.woff'. 
jquery-3.4.1.min.js:2 jQuery.Deferred exception: $(...).jtable is not a function TypeError: $(...).jtable is not a function
    at HTMLDocument.<anonymous> (https://localhost:44391/Home/Index:49:36)
    at e (https://localhost:44391/Scripts/jquery-3.4.1.min.js:2:29453)
    at t (https://localhost:44391/Scripts/jquery-3.4.1.min.js:2:29755) undefined
k.Deferred.exceptionHook @ jquery-3.4.1.min.js:2
jquery-3.4.1.min.js:2 Uncaught TypeError: $(...).jtable is not a function
    at HTMLDocument.<anonymous> (Index:49)
    at e (jquery-3.4.1.min.js:2)
    at t (jquery-3.4.1.min.js:2)

**Comment by ProblemKidS** [comment]
After I put @Url.Content it deletes the mixed issue but still i cant see anything on the web.

Uncaught ReferenceError: jQuery is not defined
    at jquery.jtable.aspnetpagemethods.js:150
jquery.jtable.js:1316 Uncaught ReferenceError: jQuery is not defined
    at jquery.jtable.js:1316
jquery-ui-1.12.1.js:14 Uncaught ReferenceError: jQuery is not defined
    at jquery-ui-1.12.1.js:14
    at jquery-ui-1.12.1.js:16
jquery.jtable.js:44 Uncaught TypeError: $.widget is not a function
    at jquery.jtable.js:44
    at jquery.jtable.js:1316
jquery-3.5.1.js:4046 jQuery.Deferred exception: $(...).jtable is not a function TypeError: $(...).jtable is not a function
    at HTMLDocument.<anonymous> (https://localhost:44352/:35:40)
    at mightThrow (https://localhost:44352/Scripts/jquery-3.5.1.js:3762:29)
    at process (https://localhost:44352/Scripts/jquery-3.5.1.js:3830:12) undefined
jQuery.Deferred.exceptionHook @ jquery-3.5.1.js:4046
jquery-3.5.1.js:4055 Uncaught TypeError: $(...).jtable is not a function
    at HTMLDocument.<anonymous> ((index):35)
    at mightThrow (jquery-3.5.1.js:3762)
    at process (jquery-3.5.1.js:3830)

**Comment by ProblemKidS** [comment]
ok i am idiot
