### ISSUE TITLE
Its not working 

### ISSUE THREAD

**Issue by ProblemKidS** [volosoft/jtable#2250]
Even If i do everything i can´t see any result on web Please Help.
This is what web console show to me:
Uncaught TypeError: $(...).jtable is not a function
    at HTMLDocument.<anonymous> (Index:61)
    at mightThrow (jquery-3.5.1.js:3762)
    at process (jquery-3.5.1.js:3830)

Query.Deferred exception: $(...).jtable is not a function TypeError: $(...).jtable is not a function
    at HTMLDocument.<anonymous> (https://localhost:44352/Home/Index:61:40)
    at mightThrow (https://localhost:44352/Scripts/jquery-3.5.1.js:3762:29)
    at process (https://localhost:44352/Scripts/jquery-3.5.1.js:3830:12) undefined

Uncaught TypeError: $.widget is not a function
    at jquery.jtable.js:44
    at jquery.jtable.js:1316

Uncaught ReferenceError: jQuery is not defined
    at jquery-ui-1.12.1.js:14
    at jquery-ui-1.12.1.js:16

Uncaught ReferenceError: jQuery is not defined
    at jquery.jtable.js:1316

Uncaught ReferenceError: jQuery is not defined
    at jquery.jtable.aspnetpagemethods.js:150

**Comment by mundattil** [comment]
i am getting the same issue. But why it is solved without a solution
