### ISSUE TITLE
Jtable 2.6.0 with error: "Cannot read properties of undefined (reading 'recordPreview')"

### ISSUE THREAD

**Issue by casanovadn** [volosoft/jtable#2273]
I'm trying to upgrade to version 2.6.0 and got this error

jquery-3.6.0.js:4059 Uncaught TypeError: Cannot read properties of undefined (reading 'recordPreview')
    at $.<computed>.<computed>._addColumnsToHeaderRow (jquery.jtable.js:3102:30)
    at $.<computed>.<computed>._addColumnsToHeaderRow (jquery.jtable.js:3474:41)
    at $.<computed>.<computed>._addColumnsToHeaderRow (jquery.jtable.js:3794:41)
    at $.<computed>.<computed>._addRowToTableHead (jquery.jtable.js:305:18)
    at $.<computed>.<computed>._addRowToTableHead (jquery-ui.js:415:25)
    at $.<computed>.<computed>._createTableHead (jquery.jtable.js:296:18)
    at $.<computed>.<computed>._createTableHead (jquery-ui.js:415:25)
    at $.<computed>.<computed>._createTable (jquery.jtable.js:286:18)
    at $.<computed>.<computed>._createTable (jquery-ui.js:415:25)
    at $.<computed>.<computed>._create (jquery.jtable.js:150:18)

Thanks for any help. Best regards

**Comment by misterparsons** [comment]
HI,

I expect you have solved your problem by now. If not and you are still having difficulty, as nothing the jtable code has changed in this region, please post your jtable definition, so that help can be offered.

Kind Regards

**Comment by DorinOctavianPopa** [comment]
Hi, 
I will try to solve this issue. I also need the facilities included in version 2.6. Wish me luck!

**Comment by ryanfriedewald** [comment]
Any update? Getting the same error when running with jQuery 3.6 and ASP.NET MVC 4
